server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:{{cookiecutter.mysql_port}}/{{cookiecutter.mysql_db_name}}?createDatabaseIfNotExist=true
    username: "{{cookiecutter.mysql_user_name}}"
    password: "{{cookiecutter.mysql_user_password}}"
    initialize: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialiect: org.hibernate.dialect.MySQL8Dialect

logging:
  file:
    name: logs/application-debug.log
  level:
    org.springframework.web: DEBUG

# you can put your custom global variables here
app:
  security:
    jwt:
      secret: "put-your-jwt-secret-here"
      duration: 86400 # a day
      issuer: "{{cookiecutter.company_name}}"
